# Generated by Django 4.0.4 on 2022-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_category_slug_remove_product_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='actual_price',
            new_name='start_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='your_price',
        ),
    ]
