# Generated by Django 4.0.4 on 2022-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_rename_actual_price_product_start_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/static/auctions'),
        ),
    ]
